### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by JJery-web** [FintelLabs/emosent-py#3]
Hi. Thanks for creating such a good package for the emoji analysis.
But I find when I use the case in py, I can not run the code successfully and it gives me the following result:

Traceback (most recent call last):
  File "E:\Python\毕业设计\test\0116test.py", line 2, in <module>
    from emosent import get_emoji_sentiment_rank
  File "D:\Anaconda3\lib\site-packages\emosent\__init__.py", line 3, in <module>
    from emosent.emosent import EMOJI_SENTIMENT_DICT, get_emoji_sentiment_rank
  File "D:\Anaconda3\lib\site-packages\emosent\emosent.py", line 68, in <module>
    EMOJI_SENTIMENT_DICT = _build_dict_from_csv(
  File "D:\Anaconda3\lib\site-packages\emosent\emosent.py", line 32, in _build_dict_from_csv
    _header_row = next(csv_reader)
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa4 in position 181: illegal multibyte sequence

**My code is:**
from emosent import get_emoji_sentiment_rank
get_emoji_sentiment_rank('❤')

How can I do please?

**Comment by JJery-web** [comment]
Ok. I deal with the issue by add

**Comment by omkar-foss** [comment]
**This above mentioned issue has been fixed in [release v0.1.7](https://github.com/omkar-foss/emosent-py/releases/tag/v0.1.7).**

You can install in via `pip` as follows:

```python
pip install emosent-py==0.1.7
```

My sincere apologies on the delayed response, I've been inactive for quite a long time due to some personal reasons. But I'm trying my best to actively maintain this project going forward. Please feel free to reopen this issue in case you still face the issue using the new release (v0.1.7). Thanks.
